# Generated by Django 6.1.1 on 2026-09-17 08:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='wishlist_users',
            field=models.ManyToManyField(blank=True, related_name='wishlist_cakes', to=settings.AUTH_USER_MODEL),
        ),
    ]
