# Generated by Django 6.1.1 on 2026-09-19 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_bakeryitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakeryGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cakes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bakery_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='products.bakeryitem')),
            ],
        ),
    ]
